### ISSUE TITLE
Symbol3 should not be Mask or Free Spin symbol in lineWin module

### ISSUE THREAD

**Issue by weihaixiaoseu** [VelbazhdSoftwareLLC/Nine-Masks-of-Fire-Simulator#5]
int symbol3 = line[0];
for (int i = 0; i < 5; i++) {    ######## line[i]!=0 && line[i]!=1 && line[i]!=2
	if (line[i] != 2) {       
	       symbol3 = line[i];    
		break;
	}
}
For example, if the line is "Wild,Wild,Wild,Mask,Mask.  Symbol3 should not be Mask,  Correct?

**Comment by TodorBalabanov** [comment]
Yes, you are correct. Masks do not participate in line wins.
